name: 📚 Documentation
description: Create a report to help us improve our documentation 📖.
labels: ["documentation"]
body:
  - type: textarea
    id: documentation
    attributes:
      label: Documentation Issue or Improvement
      description: Please describe the issue or improvement related to the documentation.
    validations:
      required: true
